services:
  s3:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    secrets:
      - minio-credentials
    networks:
      - backend
    environment:
      MINIO_CONFIG_ENV_FILE: /run/secrets/minio-credentials
      MINIO_CONSOLE_ADDRESS: ":9001"
      MINIO_BROWSER_REDIRECT_URL: "http://s3-console.unify.com"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
      start_interval: 1s

  db:
    image: postgres:18-alpine
    volumes:
      - db_data:/var/lib/postgresql:rw
      - ./config/pg:/docker-entrypoint-initdb.d:ro
    env_file:
      - secrets/pg.env
    ports:
      - "5432:5432"
    # secrets:
    #   - db-pass
    #   - db-user
    networks:
      - backend
    # environment:
    #   POSTGRES_PASSWORD_FILE: /run/secrets/db-pass
    #   POSTGRES_USER_FILE: /run/secrets/db-user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
      start_interval: 1s

  auth:
    image: supertokens/supertokens-postgresql:latest
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - secrets/pg.env
      - secrets/auth.env
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: backend/
    depends_on:
      s3:
        condition: service_healthy
      db:
        condition: service_healthy
      auth:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - secrets/pg.env
      - secrets/minio.env
    environment:
      UBD_S3_DOMAIN: storage.pterano.com
    develop:
      watch:
        - path: ./backend/src/
          action: rebuild
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
      start_interval: 1s


  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      s3:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - backend
    develop:
      watch:
        - path: ./config/nginx/
          action: restart

volumes:
  minio_data:
  db_data:

secrets:
  minio-credentials:
    file: secrets/minio.env
  # db-pass:
  #   file: secrets/postgres-pass
  # db-user:
  #   file: secrets/postgres-user

networks:
  backend:
    driver: bridge
