"""Added user table

Revision ID: 1f56885a8d48
Revises: 84027f3521a8
Create Date: 2026-06-23 16:23:37.255657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f56885a8d48'
down_revision: Union[str, Sequence[str], None] = '84027f3521a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('businesses', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, 'businesses', ['id'])
    op.create_foreign_key(None, 'businesses', 'users', ['owner_id'], ['id'])
    op.create_unique_constraint(None, 'inventory', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_constraint(None, 'businesses', type_='unique')
    op.drop_column('businesses', 'owner_id')
    op.drop_table('users')
    # ### end Alembic commands ###
