name: Deploy Product Page

on:
  push:
    branches:
      - master
    paths:
      - frontend/
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i

      - name: Build files
        run: npm run build

      # - name: create .nojekyll
      #   run: touch .output/public/.nojekyll

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: dist
