name: Test Product Page (Build)

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/

    steps:
      - uses: actions/checkout@v3

      - name: Check for frontend changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'

      - name: Install dependencies
        if: steps.filter.outputs.frontend == 'true'
        run: npm i

      - name: Build files
        if: steps.filter.outputs.frontend == 'true'
        run: npm run build
